### ISSUE TITLE
page reload issue

### ISSUE THREAD

**Issue by stoplogic** [codrops/MagneticButtons#2]
Hello! Faced a problem, when reloading a page in google chrome, the hover zone moves somewhere to the top of the page. The effect starts working normally again if you scroll to the top of the page and reload. I don’t see any point in attaching the code, I used your files and connected the demo4.e22d7780.js file to the project. I checked for conflicts with other files - I found nothing. In all other browsers, everything works as it should. Please tell me what this problem may be related to, what I did wrong.

**Comment by botelho** [comment]
Thanks for the heads up! I think we've fixed the problem. Could you try with the new version?

**Comment by stoplogic** [comment]
Thanks, but unfortunately the problem persists. I think I am doing something wrong. Should I include something other than demo4.e22d7780.js and styles for the button?

> Thanks for the heads up! I think we've fixed the problem. Could you try with the new version?

**Comment by botelho** [comment]
A bit hard to help like this. Maybe you could share a live link?

**Comment by nelrnd** [comment]
Hello I know it's a bit late but I've come across the same issue and maybe someone else will. 

To reproduce this bug, make body element 200vh, scroll a bit vertically then reload the page. When you'll hover across the button, you'll see the magnetic effect is broken. 

This happens because of the calculateSizePosition() of the ButtonCtrl class, and particularly the .getBoundingClientRect() function called inside of it. This fn will calculate the position and sizing of the button elem, but it will calculate the top position of the btn relative to the viewport and not the document. So it make the top value vary depending on the level of scroll of the page. This is what break the magnetic hover effect, because it will falsify the result of distanceMouseButton in the render() method later on.

To solve this, in calculateSizePosition(), you can do something like:
```
const rect = this.DOM.el.getBoundingClientRect()
this.rect = { left: rect.left + window.scrollX, top: rect.top + window.scrollY, width: rect.width, height: rect.height }
```
(you can't directly change the left and top values of rect because it's read only)
